### PR TITLE
Updated Working Groups and SIGs for Q1 2020

### PR DESCRIPTION
**Pull request by momack2**
Added some scaffold for our new working groups for 2020. @autonome - could you help take a pass through some of the Ecosystem & SIG "responsibilities" before we publish? @ipfs/wg-captains FYI

### CODE REVIEW

**Comment by jessicaschilling** [comment]
@momack2 @autonome -- is this ready to go? I'll need to flow the changes through to the website in https://github.com/ipfs/website/issues/357 .

**Comment by momack2** [comment]
I'm happy to merge this, with the understanding that our new WG structure will be better explained by the 2020 roadmap post I'm working on

**Comment by jessicaschilling** [comment]
@momack2 If you want to get an OK from @autonome first, please do, but otherwise merge ... I'll use that as my sign to update the website ;)

**Comment by daviddias** [comment]
Hi @momack2! I'm doing some cleanup on the research repos and found that the `research-blockchain-data` has been renamed to [`sig-blockchain-data`](https://github.com/ipfs/sig-blockchain-data). Do you want to keep it that way or should I organize those research/braintrust as well?

**Comment by momack2** [comment]
@daviddias - feel free to swap. Seemingly the only thing with that prefix, and I think research is a fine category

**Pull request merged**
