### PR TITLE
OKRs - 2019 Q2 Locol

### PR DESCRIPTION
**Pull request by momack2**
## Local Offline Collaboration Working Group OKRs
It's time for us to work on our OKRs for Q2 2019. We should keep in mind our WG goals as expressed in our [research plan](https://github.com/ipfs/local-offline-collab/blob/master/Research_Plan.md). We'll use this PR for proposals and discussions of OKRs the next quarter. 

ref #902

- [x] [Score 2019 Q1 OKRs](https://docs.google.com/spreadsheets/d/1BtOfd7s9oYO5iKsIorCpsm4QuQoIsoZzSz7GItE-9ys/edit?ts=5c2f3d49#gid=1681757723)
- [x] [Async Retrospective](https://docs.google.com/document/d/1YnCZl5MctLqHZ4zmBCLED6bUb-rOKq_5J4LQDF-fDqA/edit#heading=h.fnynpqgczeg2)
- [x] 2019 Q2 OKRs Open Planning (this thread)
- [ ] Move 2019 Q2 OKRs to [2019 Q1 OKRs Spreadsheet](https://docs.google.com/spreadsheets/d/1YSeyWqXh3ImanRrTkYQHHkCofiORn68bYqM_KTLBlsA/edit#gid=1681757723)

### CODE REVIEW

**Comment by terichadbourne** [comment]
@momack2 I think our objective "Engage with wider Local/Offline-First communities" makes a lot of sense to continue in Q2. Offline Camp (which I'm planning) and DWeb Camp will be good places to engage, but both events are in Q3. Data Terra Nemo is Q2.

Should we send someone to have chats at Data Terra Nemo in May (Q2) with offline/local use cases in mind? 

Is anyone involved in planning for DWeb Camp or should we just push that off to a Q3 attendance goal?  

I'll be continuing planning for Offline Camp (which takes place in Q3). Would this wording be appropriate for a KR? 

"Offline Camp planning is underway with 80% of attendees and sponsors booked"

**Comment by agentofuser** [comment]
@terichadbourne the Scuttlebutt crowd is the most active offline-first community I'm aware of, it might be a good idea to engage with them.

In particular, I'd love to take advantage of the existing trust relationships formed by my SSB social graph to auto-pin content shared (with ipfs-specific, to-be-developed metadata) by the peers I follow.

They have a larger intersection with dat-project developers, but there's no reason why there can't be collaboration with both.

**Comment by mikeal** [comment]
> RE: SSB

Dominic Tarr will be at DTN and so will the IPLD team, so we’ll definitely be chatting (and I’m looking forward to catching up with him personally anyway). At DWeb last year we had a “Browser Dinner” where we connected people working on browsers and standards with DWeb people and Dominic and and a few other SSB people were invited, so we’ve been trying to keep an active line of communication going for a while, it’s just a bit difficult as their stack is **so** different from ours, but they are farther along with a user facing product and I’ve had great discussions with Dominic about issues like moderation.

**Comment by momack2** [comment]
I'm also planning to attend DTN - so can happily represent there. 

@agentofuser - that suggestion sounds similar to the "Collaborative pinset" idea that ipfs-cluster was thinking about (https://github.com/ipfs/roadmap/blob/master/WG_CLUSTER.md#decentralized-web) - is this something you'd be interested to help work on? @hsanjuan and @lanzafame would be great folks to review a quick proposal if so. I agree it'd be sweet!

I'm pretty limited in my bandwidth this coming quarter, so I'm limited in the efforts I can take on. Draft below - if others like @whyrusleeping @raulk or @jimpick want to track any planned hacks/demos in our todo list for the quarter - we'd be happy to add those in here!

## Engage with wider Local/Offline-First communities
- [terichadbourne] Offline Camp planning is underway with 80% of attendees and sponsors booked
- [momack2] Form 3+ additional Local Offline Collab relationships through attendance at DTN and IPFS Camp
- [momack2] Create 1 demo, talk, or installation for IPFS Camp and future Q3 conferences
- [momack2] Increase IPFS Locol visibility and awareness with 1+ reference material (videos, posts, etc) with over 50 views

**Comment by jimpick** [comment]
I have a working hack/demo here I'd like to improve a bit:

https://github.com/jimpick/multiple-tabs-logux-peer-base

The repo is poorly named. It's an experiment to see if I could use peer-base in an iframe on a web page to synchronize requested pins between multiple web browsers and browser tabs, and between a pinning bot (saves to ipfs-cluster). I got it working with @gozala's lunet self-publishing demo! But, the demo is currently offline ... I'd like to document it a bit more with a README and a video demo, and evolve it into a "bring your own pinner" type of system.

**Pull request merged**
