### PR TITLE
Revised community wg responsibilities: WIP

### PR DESCRIPTION
**Pull request by pkafei**
This commit reflects some of the scope changes of the Community Working Group. The more pertinent changes include:

* Less focus of internal WG team building
* We are tabling our automation goals
* Less emphasis of evangelism via events and social media

At this time, we are actively revising and creating new goals for the community WG.

### CODE REVIEW

**Comment by terichadbourne** [comment]
@pkafei I think you accidentally deleted the responsibilities of the Project WG which is the section above ours. It confusingly has the word "Community" after "IPFS Project Working Group." 

I don't know whether we ought to remove ProtoSchool from this since that work will now sit in its own project, or if whoever remains on the IPFS Community WG will be contributing content ideas, etc. to the ProtoSchool project team (yours truly) on behalf of the IPFS project team so there's reason to leave it. 

Ultimately I think there's always been a disconnect in this list between what we want the WG's scope to be and what it's staffed to be.

**Comment by pkafei** [comment]
@terichadbourne Those deletions are intentional. I don't we we are maintaining the IPFS Roadmap and Vision. Also I don't think we are facilitating communication and alignment across the organization or helping async teams coordinate at scale. If I'm not mistaken the community team is more focused in meeting the needs of the PL Community. I'm not sure if we are actively supporting Long Time Contributors.

**Comment by mikeal** [comment]
We can probably remove ProtoSchool as well, we’re working on spinning that into its own top level project.

**Comment by terichadbourne** [comment]
I've removed ProtoSchool per @mikeal's suggestion and also removed "Community" from the phrase about the separate IPFS Project WG to avoid future confusion. 

Questions about these remaining items: 
- "Coordinates the communities around events, blog posts and education" & "Respond to requests for IPFS presence in conferences."  - We've not yet done any coordination around events and I was under the impression that was falling to events, but it's not been made clear across the org and we're frequently asked about it. Is someone being added to the community team to take that on or will the events team be responsible? 
- "Publish regular updates to the community (blog posts and newsletters)." & "Editorial (Blogs, Documentation)"- Is this referring to Jenn's existing workload (only the newsletter that I'm aware of) or something new that Portia or a new hire would be doing? I'm not aware of the community team having involvement in blog posts or actively improving documentation to date. There was talk on a recent communications WG call about the potential of each project team making its own hires for documentation, but I don't know if that hire would sit in community WG. 
- "Education (Demos)" - Is this where the Truffleboxes that @pkafei is excited to build would fall?

**Comment by pkafei** [comment]
> "Publish regular updates to the community (blog posts and newsletters)." & "Editorial (Blogs, Documentation)"- Is this referring to Jenn's existing workload (only the newsletter that I'm aware of) or something new that Portia or a new hire would be doing?

I believe this is in reference to Jenn's newsletters.

>  "Education (Demos)" - Is this where the Truffleboxes that @pkafei is excited to build would fall?
Merge state

We'll, see. Most likely the educational demos will showcase the IPFS use case we want to push to the broader community. I'm under the impression that they will take the form of boiler plate apps. 😊

**Comment by momack2** [comment]
This was superseded by another PR that included other org changes from early Q2 and is now out of date.

**Pull request closed without merging**
