### PR TITLE
OKRs - 2019 Q2 Web Browsers WG

### PR DESCRIPTION
**Pull request by lidel**
> Parent issue: https://github.com/ipfs/team-mgmt/issues/902 

- Add your ideas for the Web Browsers team as comments on this PR 

TODO:

- [x] [Score your 2019 Q1 OKRs with End of the Quarter Scores](https://docs.google.com/spreadsheets/d/1BtOfd7s9oYO5iKsIorCpsm4QuQoIsoZzSz7GItE-9ys/edit#gid=755202447) 
- [x] [Q1 Retrospective](https://docs.google.com/document/d/111t2yY-3msflyoBCne4mkPjaZyuQeyjC7d4-oOK5czM/edit?usp=sharing)
- [x] 2019 Q1 OKRs Open Planning (this thread)
- [x] [Move 2019 Q2 OKRs to 2019 Q2 OKRs Spreadsheet](https://docs.google.com/spreadsheets/d/1YSeyWqXh3ImanRrTkYQHHkCofiORn68bYqM_KTLBlsA/edit#gid=755202447)
    - [x] draft ideas for Q2 projects, **using the central priorities agreed** on [here](https://docs.google.com/document/d/1jqpjLRy7CtD9umDK1WzmaJVHEUqQJylwKdiYW_yTFEA/edit) as reference

@lidel @hugomrdias @autonome

### CODE REVIEW

**Comment by autonome** [comment]
# IWB Q2 Hopes & Dreams (aka OKRs)

Included P3 and greater here in order to capture all surface area covered in planning sessions, but only moved P0/P1 to the planning sheet.

Rough criteria for P values that we used in planning sessions:

* P0: Do or die for the quarter
* P1: Designed for inclusion
* P2: Ongoing expected work (longer term / co-op)
* P3: Well, we got everything else finished, so...
* P4-999: Happy accidents, or future

P0 has been estimated, and falls within reasonable amount to accomplish within the time budget alloted in the Q2 OKRs planning document.

P2 describes things like browser vendor discussions or co-op work - escape hatch for "long-running processes" or cross-wg dependencies.

## Publishing websites with IPFS

* P0: IPFS Camp: Elective course on publishing websites on IPFS

### Course work (haha)

* Special cluster
* Template for share app
* Use Oli's stuff

## Reduce surprises for web developers

* P0: CIDv1 Base32 migration is complete
* P0: JS-IPFS works in Vue-CLI projects 
* P0: JS-IPFS supports File and FileList
* P1: JS-IPFS works as expected in ESM environments
* P2: JS-IPFS can be processed by Rollup
* P2: JS-IPFS has an IndexedDB-based datastore
* P2: JS-IPFS has a Universal API provider with configurable fallback heuristics
* P3: Bundle size has not regressed
* P3: Design and create a browser global ipfs instance based on Service Worker
* P4: JS-IPFS can be included in Parcel bundles
* P4: HTTP API/Gateway has interoperability tests
* P4: Lazy-loaded IPFS Proxy entrypoint is exposed to websites, the old API is removed 
* P4: Research and design IPFS provider for progressive peer-to-peer web applications (PPWA)

## Browsers are integrating IPFS and shipping it

* P0: We've defined what success is for native support in browsers, and have a long term strategy proposal for getting there
* P0: HTTP Proxy mode is supported by JS IPFS and Companion (blocking Brave)
* P0: Brave: UI for new embedded node type exists in Companion
* P0: Brave: Companion uses embedded HTTP gateway (JS IPFS) by default
* P1: Brave: Embedded JS IPFS node is using P2P TCP based Transport
* P1: Brave: Embedded JS IPFS node performs mDNS-based Local Discovery
* P1: We've defined a strategy for standards body participation and influence
* P1: We've got a plan and roadmap with Opera
* P2: arewedistributedyet.com is collapsed to signposting (notes below)
* P3: We've hired an engineer to work on browser codebases

### UI for new node type
* Welcome screen text changes
* Button for starting/stopping local node
* UI for reflecting presence of advance features

## Companion can support archiving of web content

*Background: This objective is a first take at reorienting strategy for Companion feature development around a set of use-cases for non-developer users in browsers.*

* P0: We've identified the primary non-developer use-cases in web browsers, to drive strategy for the WG
* P0: User actions add content to MFS by default
* P1: User is able to save full snapshot of a website to IPFS
* P2: Redesigned user experience for pinning (collab with GUI/Design WG)

## Support alternative environments

* P0: JS-IPFS can be bundled in Electron
* P2: JS-IPFS can be included and run in a React Native project

## Notes: Companion use-cases for non-technical users

* Archiving
  * dependencies
    * mfs (blocker)
    * stripping text
  * co-op wins with other WGs
  	* offline wg - supports offline viewing of saved content
* Publishing
  * dependencies
    * mfs (blocker)
    * ipns
* Sharing
  * dependencies
    * mfs (nice to have)
    * archiving (blocker)

## Notes: Add to backlog

* pinning / saving ux and language
* package manager (i know this hash!)
* what decentraleyes does

## Notes: AWDY

* high value collaborators use it
* but been some quarters since updated
* gets regularly deprioritized
* website needs something to happen
* can collapse content to signposting, so doesn't appear abandoned?

**Comment by momack2** [comment]
Thanks for the update @autonome - can you notate which if any of these are critical needs for package managers / users of ipfs-based package managers? As @daviddias points out, a broad definition of package managers could also include using ipfs to fetch (and save for later) the contents of script tags - which sounds related to the objectives around saving websites offline for later access/interaction. Our browser work is really strategic from an adoption and community support perspective, but should still include some threads pushing strongly on our top priority for the year.

**Comment by autonome** [comment]
IIRC @lidel and Andrew discussed this, but there are dependencies on better
browser support. We'll remix these in the next pass  to make the package
manager bits more explicit.

**Comment by autonome** [comment]
Changes after discussion so far:

* Removing HTTP proxy work, as is dependent on Go team prioritizing, and they've pushed.

* Adding objective for Package Manager work, with P0 key result for improving IPNS performance in browsers, and a P2 key result for a prototype of an Unpkg clone based on IPFS.

* IPFS Camp objective had the *elective* but not the primary course, so we need to add that one still.

**Comment by autonome** [comment]
OKRs comment is now updated with the changes above, and also synced to spreadsheet.

**Comment by momack2** [comment]
Note that there is also active IPNS work being owned by @aschmahmann and
@pdte - coordinate there to make sure we aren’t duplicating efforts across
wgs!

**Comment by autonome** [comment]
Roger! Everyone is already in the IPNS tiger team room, and that coordination is happening.

**Comment by autonome** [comment]
@momack2 How do we finalize these? By merging the issue? Any further review steps needed?

**Comment by autonome** [comment]
Oh, and I recorded a video summary last week, and put it in the drive folder!

**Comment by momack2** [comment]
Thanks @autonome! yes, just merge this thread. What folder did you put the video in? I can't find it!

**Comment by autonome** [comment]
I don't have the permissions to merge here, which we haven't figured out yet... I'll ping IT about it.

I put the video [here](https://drive.google.com/drive/folders/1SWauTkN0jETGsNmH7fzGJPLLp2AL_-TK), which I read is the right place... but I can't find which document I read it in now 😅

**Pull request merged**
