### PR TITLE
Q3 OKR Planning for Project Operations

### PR DESCRIPTION
**Pull request by momack2**
## Success Goals/Metrics for Q3:
Goal: IPFS Implementations are shipping quality releases on a schedule (Alan, Steven)
- IPFS is shipping at a rate that meets the needs of the task forces
- IPFS releases are shipped on a regular schedule
- Lead maintainers are reducing bus factor and increasing velocity by leveling-up contributors into more responsibility
- Projects have systematized their operation (eg issue triage, response time, etc)
- Engineering design review creates early alignment on protocol improvements
- Metric: Shipped a release policy, with a release that went through all stages
- Metric: Merges increased by 10%? Mean time to review decreased by n%?

Goal: Collaborations are systematized and prioritized (Dietrich, Arkadiy)
- Brave has shipped IPFS Companion support
- We're testing initial builds from Opera
- ENS improves UX of pointing at IPFS/IPNS/IPLD content paths from smart contracts
- Opportunities are classified, prioritized and serviced in a pipeline process
- We know who's using IPFS and support them

Goal: The IPFS Community is informed of relevant news in a timely manner (Molly, Dietrich)
- We define and start measuring a metric for tracking community support needs
- We proactively update the community about project news
- We have a communications runbook
- We coordinate at least 3 collaboration posts
- Backlog of blogs are being blogged
- Metric: Published one blog post per month for the quarter

Goal: Lower priority projects are clearly owned and maintained (Dietrich)
- Desktop and WebUI are stable and usable

Goal: Research is projecting the present into the future (David)
- IPFS & libp2p team’s get a Workshop (through Zoom) with a Survey on the state of the art around P2P
- Deliver an IPFS Workshop at ACM/ICN
- You've read our new publication: State of Research in IPFS & Libp2p

### CODE REVIEW

**Comment by daviddias** [comment]
@momack2 just to confirm I understand the Protocol. Will the above [Goals/Objectives be moved to the spreadsheet](https://docs.google.com/spreadsheets/d/1AiNUL7vK5Jp8aa839UaMaI_AlBU5r6Bor-A40179I2A/edit#gid=1562851442) to be reviewed there?

**Comment by Stebalien** [comment]
> Goal: IPFS Implementations are shipping quality releases on a schedule (Alan, Steven)

I'm not sure if we'll be able to say "on a schedule" if we ship one release but we can at least set the quality bar.

**Comment by momack2** [comment]
correct, these are to be moved to the sheet for further refinement. Note, we need to have them finalized by wednesday. I think all of these could be made significantly more precise - so I'd encourage people to be as metric / measurability oriented as possible (no idea how to measure something like "stable and usable" - let's try to make this more like ">98% uptime" / "avg time to bug fix" / etc

**Comment by alanshaw** [comment]
Thank you @momack2 and all others involved for putting these together ❤️

> Metric: Merges increased by 10%? Mean time to review decreased by n%?

I think merges increasing by 10% might be a metric we'll observe by changing the release process but I'd rather not set it explicitly in case it encourages quantity over quality.

I'd like to see:

1. Time to first engagement with PR/issue is < 1 day (set expectations, convey appreciation)
2. Time to initial PR review is < 3 days (a reasonable time frame to remain fresh in mind)
3. Ideal time to PR merge/close is < 5 days (understanding that this depends on contributor)

I'd like a 🤖 to help me keep to this schedule.

> Metric: Shipped a release policy, with a release that went through all stages

Metric: Shipped a release policy, **and** a release that went through all stages

**Comment by autonome** [comment]
Updated collabs KRs:

- Brave users can share and discover data with JS-IPFS embedded node
- Opera is receiving the support they need for implementation
- ENS ships a mutable naming service using IPFS, improving the developer experience of pointing at IPFS/IPNS/IPLD content paths from smart contracts
- Opportunities are classified, prioritized and serviced in a pipeline process
- Daily operations of collabs are supported by tooling and process that enables prioritization, metrics and manageable level of daily overhead
- We have a single list of who is using IPFS and can use that information to make decisions

**Comment by autonome** [comment]
Updated Maintenance KR:

Desktop and WebUI remain functional, have a lower maintenance overhad, and are updated to meet high priority needs

**Comment by autonome** [comment]
Updated Community KRs:

- We define and start measuring a metric for tracking community support needs
- We have a blog content plan and schedule, covering Camp content, important news, collaborations and recent event participation
- We proactively update the community about important news and project progress
- We have a communications runbook for common and emergency situations

**Comment by momack2** [comment]
Suggestions for improving "shipping quality releases":
- Collaborations & other WGs aren’t blocked on core implementation release schedule for feedback/iteration/launches (P1)
- We have documented lead maintainers for all active go and js repos (P2)
- Core implementation testing gives us automated feedback on build quality on a per PR, per nightly, and per release basis (P0)
- Go and js implementations have systematized operation policies (eg issue triage, response time, etc), and a github bot to automate reminders (P1)
- We have a documented engineering design review process and send 1+ protocol improvement through the process to gain early alignment (P1)
- Ship a release policy and defined quality bar, and send 1+ release through all stages (P0)

**Comment by momack2** [comment]
I transferred this to the sheet: https://docs.google.com/spreadsheets/d/1AiNUL7vK5Jp8aa839UaMaI_AlBU5r6Bor-A40179I2A/edit#gid=1562851442

Now it needs priorities and owners - please help update y'all!

**Pull request merged**
