### PR TITLE
OKRs - 2019 Q1 DDC WG

### PR DESCRIPTION
**Pull request by pgte**
refs #792 

- [x] [Score 2018 Q4 OKRs](https://docs.google.com/spreadsheets/d/139lROP7-Ee4M4S7A_IO4iIgSgugYm7dct620LYnalII/edit#gid=412099511)
- [x] [Async Retrospective](https://docs.google.com/document/d/1Zw7EHyCP2uamxOVHsVH3rRAnZOyBJczQ9CuvdOpnLO4/edit)
- [x] 2019 Q1 OKRs Open Planning (this thread)
- [ ] Move 2019 Q1 OKRs to 2019 Q1 OKRs Spreadsheet

@jimpick @satazor @marcooliveira @aschmahmann @andreforsousa @parkan 

Temporary working doc: https://docs.google.com/document/d/1bqx4K90C8ZIqkt8LrQJrhCE25Xtm7OQlO5iQBl6gkpM/edit

### CODE REVIEW

**Comment by pgte** [comment]
@parkan @jimpick @flyingzumwalt @andreforsousa @marcooliveira can I get your EOQ scores [here](https://docs.google.com/spreadsheets/d/139lROP7-Ee4M4S7A_IO4iIgSgugYm7dct620LYnalII/edit#gid=412099511)?

**Comment by pgte** [comment]
@jimpick @parkan @satazor @marcooliveira @andreforsousa can I get your 2018 Q4 retrospective [here](https://docs.google.com/document/d/1Zw7EHyCP2uamxOVHsVH3rRAnZOyBJczQ9CuvdOpnLO4/edit#heading=h.1xrdg4st69mx)?

**Comment by satazor** [comment]
I will try to fill these ASAP, currently in transit which doesn't help.

**Comment by pgte** [comment]
Meeting to decide on first draft of OKRs is scheduled for:
Monday, December 17, time:

* 18:00 CET
* 17:00 WET (Lisbon / Porto)
* 10:00 EST

Please ping me if you want an invite.

If you cannot attend, please leave your comments / opinions here.

/cc @parkan @jimpick @andreforsousa @marcooliveira @satazor

**Comment by pgte** [comment]
adding @aschmahmann (sorry I missed you, copy-pasta error)

**Comment by satazor** [comment]
@pgte I've filled the scorings and I will do the retro tomorrow as today I'm completely overwhelmed.

Regarding the focus of the next quarter, they look right, but we will discuss in a few hours.

**Comment by pgte** [comment]
Open planning brainstorm and preliminary OKRs being done [here](https://docs.google.com/document/d/1bqx4K90C8ZIqkt8LrQJrhCE25Xtm7OQlO5iQBl6gkpM/edit#).

**Comment by pgte** [comment]
Estimate of my available time in 2019Q1 (inspired by [this](https://github.com/ipfs/team-mgmt/issues/792#issuecomment-448104872)):

* 13 weeks in the quarter - 65 days (assuming 5 day work week)
* Take out the first 2 days (NYE and Jan 1) - 63
* 10 days of Vacation + Hack Weeks + conferencing, etc. Then you have left 53 days.
* 53 days in a 8 hour work day is 424 hours
* 60% of that is 254.4 hours

**Comment by pgte** [comment]
@marcooliveira @parkan @aschmahmann @andreforsousa Thanks for the retrospective!
We're just missing @satazor @jimpick right now.

**Comment by marcooliveira** [comment]
Finally got around to filling my retrospective, scores already done previously.

**Comment by satazor** [comment]
I will take care of that tomorrow morning.

**Comment by pgte** [comment]
I've tentatively assigned priorities and owners to the KRs in [the KR doc](https://docs.google.com/document/d/1bqx4K90C8ZIqkt8LrQJrhCE25Xtm7OQlO5iQBl6gkpM/edit?ts=5c199a01). I've tagged possible owners on this doc to confirm it.

**Comment by satazor** [comment]
@pgte just finished my retro

**Comment by momack2** [comment]
Hi DDC working group! I've helped move your draft OKRs into the [planning OKR sheet](https://docs.google.com/spreadsheets/d/1BtOfd7s9oYO5iKsIorCpsm4QuQoIsoZzSz7GItE-9ys/edit#gid=412099511) - can you all please review and make sure these are still the OKRs you plan to commit to for the quarter? You have *a lot* in the peerbase bucket - so if there are any you know you can't achieve, I'd suggest moving them to the "Deferred until Q2" section beneath line 58 as we've done on a few other teams. We're aiming to get these finalized ASAP - so please go ahead and merge this PR once we have 👍s.

@jimpick @satazor @marcooliveira @aschmahmann @andreforsousa @parkan

**Comment by pgte** [comment]
Given the IPFS de-scoping on the way, I think that the DDC roadmap and OKRs no longer make sense, and so it's my opinion is that we shouldn't spend any more cycles discussing these.

**Pull request merged**
