### PR TITLE
Create 2019-04-24--gui-and-in-web-browsers-weekly.md

### PR DESCRIPTION
**Pull request by autonome**
cc #790

### CODE REVIEW

**Comment by autonome** [comment]
Thanks for fixups @lidel. I tried a different gdocs->md converter... I want a better one. Or to move to hackmd or something not gdocs 😅

**Comment by lidel** [comment]
@autonome @olizilla I believe use of gdocs was copied from IPFS Weekly call somewhere in 2018, but various practices changed since then. For example, go and js weekly calls both use http://cryptpad.fr/ now:

- JS Weekly: https://github.com/ipfs/team-mgmt/issues/650#issuecomment-487520845
- GO Weekly: https://github.com/ipfs/team-mgmt/issues/674#issuecomment-487686381

We could replace link to gdoc with link to https://github.com/ipfs/team-mgmt/issues/790, and do what JS and GO do (post new cryptpad link every week). Not the best, but at least it would unify experience for people attending all three calls. 

Thoughts?

**Comment by terichadbourne** [comment]
I think I was one of the people who pushed for us to use gdocs to create a low barrier to entry for call attendees in terms of providing familiar tools and one-click access. 

I still find it unfriendly to the meeting attendee to do something that can’t provide a one-click link from the meeting invite to the notes (as in the JS and go meetings), and I think it’s more important to prioritize the experience of all the people attending calls than the one doing admin work afterward. (When I’m responsible for notes the only thing I have to fix manually after that conversion tool is putting back in the spaces it deletes before every link.)

I also personally prefer having at least a few meetings worth of notes in the same place as each other so I can scroll down and quickly see and/or copy my previous entries as I try to remember what’s new for this week.

**Comment by fsdiogo** [comment]
I'm in favour of using CryptPad or something that supports markdown out of the box, as converting from google docs to markdown is always a hassle.

I also like the flow of the JS Weekly (https://github.com/ipfs/team-mgmt/issues/650), having only one issue that gets a new comment per weekly sync with the link to the zoom and the new notes.

**Pull request merged**
