### PR TITLE
OKRs - 2019 Q4 Docs WG

### PR DESCRIPTION
**Pull request by jessicaschilling**
refs #1033 

- [x] [Score 2019 Q3 OKRs](https://docs.google.com/spreadsheets/d/1AiNUL7vK5Jp8aa839UaMaI_AlBU5r6Bor-A40179I2A/edit#gid=1841105909) 
- [x] [Define draft Q4 2019 OKRs](https://hackmd.io/0W3Yx-05QKyWad_uoqz32g)
- [x] Refine and finalize Q4 2019 OKRs (this thread, your comments welcome!)
- [x] Move final OKRs to [2019 Q4 OKRs Spreadsheet](https://docs.google.com/spreadsheets/d/1VeyiLvBdX_PrP394kU_lwkQZxfNwqMVX1f7K4ursSPM/edit#gid=1841105909)

cc @ericronne @cwaring @dominguesgm @terichadbourne

### CODE REVIEW

**Comment by terichadbourne** [comment]
@jessicaschilling Just a heads up that I've added my scoring to my line in the Google-based Q3 OKRs.

**Comment by jessicaschilling** [comment]
@terichadbourne Thank you!

**Comment by terichadbourne** [comment]
For reference, the [draft of Q4 OKRs](https://github.com/ProtoSchool/roadmap/pull/24/files#diff-8f627f4ca04814ed0454fd08d6b7899b) for ProtoSchool, which extend beyond IPFS docs-related work. (Still a work in progress to complete by end of next week.)

**Comment by ericronne** [comment]
I ❤️the markdown-gridded OKRs!

**Comment by jessicaschilling** [comment]
Issues moved to Q4 spreadsheet: https://docs.google.com/spreadsheets/d/1VeyiLvBdX_PrP394kU_lwkQZxfNwqMVX1f7K4ursSPM/edit#gid=1841105909
Closing this issue.

**Pull request merged**
